PaulinePRS/books4rent

Gemfile, Gemfile.lock, app/models/book.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200530135656_devise_create_users.rb, db/migrate/20200530140139_add_columns_to_users.rb, db/migrate/20200530142334_create_books.rb, db/schema.rb, test/models/book_test.rb, test/models/user_test.rb
Added User model
Added Book model
=> Models creation

app/controllers/books_controller.rb, app/views/books/_form.html.erb, app/views/books/new.html.erb
J'ai ajouté :
- action new dans le contrôleur
- new.html.erb
- _form partial dans books > views
=> added books#new and associated view (using form partial)

app/controllers/books_controller.rb, app/views/books/index.html.erb
On a crée la méthode index dans le controller, puis on a crée le fichier "index.html.erb" pour afficher tous les books sur la page index. 
On a pas du tout fait de front pour le moment :) 
On a mis un lien de redirection vers la show!
=> index is working

app/controllers/books_controller.rb, app/views/books/show.html.erb
Adding the view and the controller method for show
=> Add view of the show page

app/controllers/books_controller.rb
=> books#create

app/controllers/books_controller.rb, app/policies/book_policy.rb
J'ai modifié la policy pour pouvoir accéder au /new en étant loggé
=> added action-new authorization

app/controllers/books_controller.rb, app/views/books/show.html.erb
*ajout de la method + affichage de l'icone poubelle. 
Passage en Français du CTA reviews + retour à la liste
=> adding delete method

app/controllers/pages_controller.rb, app/views/books/show.html.erb
*replacer cta + retour dans divs.
=> fix front elements

app/controllers/books_controller.rb, app/policies/book_policy.rb
=> delete methold is ok

app/controllers/books_controller.rb, app/policies/book_policy.rb, app/views/books/edit.html.erb, app/views/books/index.html.erb, app/views/layouts/application.html.erb
J'ai ajouté la méthode update & edit dans le controller et dans la view
=> Edit a book

app/models/booking.rb, app/models/user.rb, db/migrate/20200604171805_create_bookings.rb, db/schema.rb, test/models/booking_test.rb
=> added booking model

app/controllers/books_controller.rb
=> fix book params

app/views/devise/sessions/new.html.erb
=> Improve front

app/models/book.rb, app/views/books/_form.html.erb, app/views/books/new.html.erb
- ajout de validations au model book
- modification du form new book
=> added validations on book model and modified new form

app/views/books/index.html.erb
J'ai mis des petites étoiles sur ratings ⭐️
=> stars to ratings

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js
javascript fix for maps & calendar
=> javascript fix for maps & calendar

app/views/books/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> Update show front

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
- modif background color dans les configs rails
-couleur de footer (pas réussi à le fixer en bas, je ferai un ticket)
-modif box search + fix affichage emoji + essais de style
=> style on home#page

Gemfile, app/javascript/packs/application.js, app/javascript/plugins/fetch_books.js, app/javascript/plugins/flatpickr.js, app/javascript/plugins/get_current_position.js, app/views/books/_form.html.erb, app/views/layouts/application.html.erb, db/schema.rb
added description field to new form
fill address field in new form with current position
remove margin bottom from footer
ensure envdot gem is loaded before cloudinary
remove console.logs
created autocomplete function in new form
improve autocomplete
=> General improvments

app/views/books/show.html.erb
- Addind the map in a div, don't work with the book location, need to work on it with a backdev Rocket! 
-Fixing some minor style bugs 
-adding bold on title and italic on author (remember your french lessons. !)
Good WE :D
=> working on style and map

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card-style.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.css, app/assets/stylesheets/pages/_show.scss, app/javascript/plugins/fetch_books.js, app/views/books/index.html.erb, app/views/books/show.html.erb, app/views/layouts/application.html.erb
map on the right of index page
design books grid
=> improve general front

app/controllers/books_controller.rb
- Replaced ILIKE by @@ in the books controller in Index method so that we can search separated keywords. ex "Potter Harry Prince" give now results
=> improved search

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_map.css, app/controllers/books_controller.rb, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/init_mapbox.js, app/views/books/_infowindow.html.erb, app/views/books/index.html.erb, app/views/books/show.html.erb, package.json, yarn.lock
- ajout d'une popup quand on clique sur un marquer de la map (+ un lien dans la popup qui amène direct sur la show du book)
- ajout d'un input de recherche sur la map pour pouvoir zoomer sur une zone
- ajout d'un autocomplete sur cet input
=> added map improvements

app/assets/stylesheets/components/_card-style.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb
show the 3 categories
center the 3 cards with d-flex bootstrap
add a hover on the cards
=> show categories

app/controllers/books_controller.rb, app/javascript/plugins/fetch_books.js, app/models/book.rb, app/views/books/_form.html.erb, app/views/books/show.html.erb, db/migrate/20200609185049_remove_publisher_from_books.rb, db/migrate/20200609190256_remove_published_date_from_books.rb, db/schema.rb, db/seeds.rb
- Migration to remove Published_date from Books
- Migration to remove Publisher from Books
- Modified Seed files 
- Modified many views 
- added a validates on Photo for land a book forms 
don't forget 
rails db:drop db:create db:migrate db:seed
=> removed published date & publisher

db/seeds.rb
- Fixed a problem with the seed
=> fixed Seed

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/layouts/application.html.erb, app/views/users/show.html.erb, config/routes.rb, test/controllers/users_controller_test.rb
- added a link "My Books" in the navbar
- added a display page for "My Books" 
- added devise policy allow user to see its own books and prevent him from seeing others
=> Create show user books

app/controllers/books_controller.rb
Lorsque l'on cherche un livre qui n'existe pas, on affiche un pop up "ce livre n'existe pas"
=> nil search

app/controllers/books_controller.rb, app/javascript/plugins/fetch_books.js, app/models/book.rb, app/views/books/_form.html.erb, app/views/books/show.html.erb, db/migrate/20200611182218_add_cover_url_to_books.rb, db/schema.rb
- added cover fetch
- display cover to user in form
=> Fetch cover

app/views/books/index.html.erb
Added some fixes to the index pages so that we can show the image even if it's one from internet
=> added some fixes to the index page

app/controllers/pages_controller.rb
=> add rating desc

app/controllers/books_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/views/books/show.html.erb
=> fix both maps

app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_index.scss, app/views/pages/home.html.erb, app/views/pages/top.html.erb
- Added grow effect to cards on home page & top books
=> added grow to card on home page
